### PR TITLE
Fix program type for loyalty program

### PR DESCRIPTION
**Pull request by DenisMela**
**Checklist:**
- [ ] Changed package version (must be higher than **master**)
- [ ] Updated README (if applicable)

### CODE REVIEW

**Review by ralph-dev — APPROVED** [review]
LGTM, was this the only place?

**Comment by DenisMela** [comment]
@ralph-dev Yep searched for program_type only found one with string

**Comment by ralph-dev** [comment]
kk feel free to merge

**Comment by ralph-dev** [comment]
@dannybuii update the Dashboard SDK version so we can merge your PR, you no longer need the omit utility now that it's fixed

**Pull request merged**
